apiVersion: v1
kind: Namespace
metadata:
  name: m2a-alpha
  labels:
    name: m2a-alpha
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-alpha
  namespace: m2a-alpha
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: m2a-alpha
  name: edit-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
- apiGroups: ["extensions"]
  resources: ["deployments", "daemonsets", "replicasets"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-alpha-binding
  namespace: m2a-alpha
subjects:
- kind: ServiceAccount
  name: team-alpha
  namespace: m2a-alpha
roleRef:
  kind: Role
  name: edit-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: team-alpha-secret
  namespace: m2a-alpha
  annotations:
    kubernetes.io/service-account.name: "team-alpha"
type: kubernetes.io/service-account-token
